# Generated by Django 4.2.30 on 2026-04-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repertoire_slug', models.CharField(db_index=True, max_length=200)),
                ('fen_normalized', models.CharField(max_length=100)),
                ('fen_full', models.CharField(max_length=100)),
                ('expected_uci', models.CharField(max_length=10)),
                ('expected_san', models.CharField(max_length=20)),
                ('played_uci', models.CharField(blank=True, max_length=10)),
                ('played_san', models.CharField(blank=True, max_length=20)),
                ('count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('first_game_id', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['-count', '-last_seen'],
                'indexes': [models.Index(fields=['repertoire_slug', '-count'], name='repertoire__reperto_263301_idx')],
                'unique_together': {('repertoire_slug', 'fen_normalized')},
            },
        ),
    ]
